// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceType } from "./DeviceType";

export type EndpointInfo = { fullname: string, id: string, name: string | null, ip: string | null, port: string | null, rtype: DeviceType | null, present: boolean | null, 
/**
 * BLE-discovered receiver: its Bluetooth address (for opening an L2CAP CoC).
 * `None` for mDNS / WiFi-LAN endpoints, which carry ip+port instead.
 */
bt_address: string | null, 
/**
 * BLE L2CAP PSM advertised by a "visible to everyone" receiver. `None` for
 * mDNS / WiFi-LAN endpoints.
 */
psm: number | null, };
